[package]
name = "dione-lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adler = "1.0.2"
seahash = "4.1.0"
lz4_flex = "0.8.2"

[dev-dependencies]
criterion = "0.3.4"

[[bench]]
name = "hashing_benchmark"
harness = false